server:
  port: 8180

spring:
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Project1
    username: bestuser
    password: Password123!
    driver-class-name: com.mysql.cj.jdbc.Driver

